# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [(modulesPath + "/installer/scan/not-detected.nix")];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel" "wl"];
  boot.extraModulePackages = [config.boot.kernelPackages.broadcom_sta];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/e8b7ccab-99c8-424c-9f9c-0a04a038f509";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."nixos".device = "/dev/disk/by-uuid/c32fe1ac-3421-45e6-8a71-371e97f79ed4";

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/f88e00bf-7795-4721-93c9-93d8467a7056";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."home".device = "/dev/disk/by-uuid/455987d1-8d6c-467b-a974-198a062aea5e";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/26E4-630A";
    fsType = "vfat";
options = [ "fmask=0077" "dmask=0077" "defaults" ];
  };


  swapDevices = [{device = "/dev/disk/by-uuid/1586e7d6-16d0-4b9d-9ba8-0489a9d7e28f";}];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp62s0u1u3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
  # high-resolution display
}
