#!/usr/bin/env python3
"""One-off: propose docs/<feature>/<kind>.md destinations for existing docs.

Prints a markdown table (current -> proposed, git-tracked?) plus a COLLISIONS
section where several sources map to one destination. This is a PROPOSAL for a
human to review and edit before any file moves. Conservative by design:
flat reference docs default to <name>/notes.md, and multi-date superpowers docs
of the same kind collide (resolve with: newest = <kind>.md, older =
<kind>s/<date>-<slug>.md).
"""
import os
import re
import subprocess
import sys

REPO = sys.argv[1] if len(sys.argv) > 1 else "."
DATE = re.compile(r"^(\d{4}-\d{2}-\d{2})-(.+?)(?:-(design|plan|notes))?\.md$")


def tracked(rel):
    r = subprocess.run(["git", "-C", REPO, "ls-files", "--error-unmatch", rel],
                       capture_output=True)
    return r.returncode == 0


def propose(rel):
    parts = rel.split("/")
    name = parts[-1]
    if parts[:2] == ["docs", "superpowers"]:
        kindmap = {"specs": "spec", "plans": "plan", "handoffs": "handoffs"}
        kind = kindmap.get(parts[2], "notes")
        m = DATE.match(name)
        feature = m.group(2) if m else name[:-3]
        if kind == "handoffs":
            return "docs/{}/handoffs/{}".format(feature, name)
        return "docs/{}/{}.md".format(feature, kind)
    # flat docs/<name>.md reference docs -> propose feature=<name>, kind=notes
    return "docs/{}/notes.md".format(name[:-3])


rows = []
for root, _, files in os.walk(os.path.join(REPO, "docs")):
    for f in files:
        if not f.endswith(".md"):
            continue
        rel = os.path.relpath(os.path.join(root, f), REPO)
        if rel.startswith("docs/affine-docs-sync/"):
            continue
        rows.append((rel, propose(rel), "yes" if tracked(rel) else "no"))

rows.sort()

print("# Migration mapping (PROPOSED -- review & edit before moving)\n")
print("Generated by scripts/affine-sync/migrate_map.py. Edit the `proposed`")
print("column, then Task 16 executes the approved moves. Groupings are")
print("conservative; adjust subjective ones (see the notes below the table).\n")
print("| current | proposed | tracked |")
print("|---------|----------|---------|")
for a, b, c in rows:
    print("| {} | {} | {} |".format(a, b, c))

# collisions: several sources -> one destination
dests = {}
for a, b, _ in rows:
    dests.setdefault(b, []).append(a)
collisions = {d: s for d, s in dests.items() if len(s) > 1}
print("\n## Collisions (multiple sources -> one destination -- MUST resolve)\n")
if collisions:
    for d, srcs in sorted(collisions.items()):
        print("- `{}` <= {}".format(d, ", ".join("`%s`" % s for s in srcs)))
    print("\nResolution rule: newest = `<kind>.md`, older = "
          "`<kind>s/<date>-<slug>.md`.")
else:
    print("(none)")

print("\n## Subjective groupings to double-check\n")
print("- thanatos-family docs (gaming/drive/perf/kanata) -- confirm feature names.")
print("- flat reference docs defaulting to `<name>/notes.md` -- some may be")
print("  better as `spec.md`/`runbook.md`/`recipes.md`.")
print("- Total sources: {}, unique destinations: {}, collisions: {}.".format(
    len(rows), len(dests), len(collisions)))
