# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [(modulesPath + "/installer/scan/not-detected.nix")];

  boot.initrd.availableKernelModules = [
    "mpt3sas"
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "sr_mod"
  ];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  # fileSystems."/" = {
  #   device = "/dev/disk/by-uuid/fd299e11-76ca-44f0-944c-fbbfbd322af4";
  #   fsType = "btrfs";
  #   options = ["subvol=root"];
  # };
  #
  # boot.initrd.luks.devices."crypt-nixos".device = "/dev/disk/by-uuid/02c36f33-a4ff-495a-b15a-1cac14b5779f";
  #
  # fileSystems."/home" = {
  #   device = "/dev/disk/by-uuid/fd299e11-76ca-44f0-944c-fbbfbd322af4";
  #   fsType = "btrfs";
  #   options = ["subvol=home"];
  # };
  #
  # fileSystems."/nix" = {
  #   device = "/dev/disk/by-uuid/fd299e11-76ca-44f0-944c-fbbfbd322af4";
  #   fsType = "btrfs";
  #   options = ["subvol=nix"];
  # };
  #
  # fileSystems."/persist" = {
  #   device = "/dev/disk/by-uuid/fd299e11-76ca-44f0-944c-fbbfbd322af4";
  #   fsType = "btrfs";
  #   options = ["subvol=persist"];
  # };
  #
  # fileSystems."/var/log" = {
  #   device = "/dev/disk/by-uuid/fd299e11-76ca-44f0-944c-fbbfbd322af4";
  #   fsType = "btrfs";
  #   options = ["subvol=log"];
  # };
  #
  # fileSystems."/boot" = {
  #   device = "/dev/disk/by-uuid/206D-E03B";
  #   fsType = "vfat";
  # };

  fileSystems."/zbackup/backup" = {
    device = "zbackup";
    fsType = "zfs";
    options = ["x-systemd.device-timeout=infinity" "x-systemd.mount-timeout=infinity" "nofail"];
  };

  fileSystems."/zmedia/media" = {
    device = "zmedia";
    fsType = "zfs";
    options = ["x-systemd.device-timeout=infinity" "x-systemd.mount-timeout=infinity" "nofail"];
  };

  # swapDevices = [{device = "/dev/disk/by-uuid/a797d72d-d44c-4aab-aa4a-9187dda515bf";}];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp9s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp7s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
