hello: ENC[AES256_GCM,data:OQb1aG/rNBytrRowjUvE39ffO2edI6KZXJ3j8fTW7FzBLDLBFcR6b+PrKfy6Ow==,iv:5scOP1kKVauudp376bn5D0gjdt/fD1jiAiXDUoWRhLE=,tag:tLPRKOzAs7t1kUAB+bemZw==,type:str]
example_key: ENC[AES256_GCM,data:/Ckii9i1vg61wLzSEQ==,iv:Kdas9TL4fBsVMRpqFHCnJ17IxRmklKAEMqQS4NUxlXw=,tag:XXdpR8Uswa0rMrsT4tKzSQ==,type:str]
#ENC[AES256_GCM,data:Kd5kFBV2qpifVt02hgeTtg==,iv:dlID0fvxsf3fH9mXjTAo/l0PaQ5b9Y6/wQmWlHzJNtk=,tag:DhDY3polpxlFf7lYip6BJg==,type:comment]
example_array:
    - ENC[AES256_GCM,data:ouN9W9Dll7Z0ad8dE/U=,iv:dmulkXzt8+M5Zzr/C4LifZUCtbsyZrZG6bYvqJ1ahX8=,tag:CH/ZcFqQldI97sSDNQDCJw==,type:str]
    - ENC[AES256_GCM,data:9TU/FcDWkzmPbjpNKNA=,iv:v8/AneZR9LbBXpQqrT+TR2Y1JZ7lXHUEVXiNVZjYSXk=,tag:1VFBqrOuYHhIooQUKCq9PA==,type:str]
example_number: ENC[AES256_GCM,data:7INctrgXt+dOvQ==,iv:wiSh4jwwm6bsY7M8/imyzRVyBrgOQz3e4td/elNixFM=,tag:rLZBlZhonLKl5BN7AIAOJA==,type:float]
example_booleans:
    - ENC[AES256_GCM,data:HXX4Kw==,iv:u1rn5OYZxypO1Tq9neTNxczqBqSIu+o57E0xclYGVkw=,tag:V0pyz2SSHapoGilaDmrR0A==,type:bool]
    - ENC[AES256_GCM,data:oG1gg5k=,iv:XR4pU0iQrQFOSez4Ly2m7cy+PSrQLsxBUg6zvxKowSU=,tag:ATr0zBGK2d0Ntqgn//QFFA==,type:bool]
michael-password: ENC[AES256_GCM,data:iBhmAyIVDKJTEcRnGvcsR4jKxrb+tGTjoUbvz64rVjL+XJdfgyLIl2mHn32mLw6lqtReiG9g2+OMpFuEjuk6vHsGlbJxPgNHecs=,iv:OqokpEeiJvW7CFZ5ebRG0JVCbIcLfTa05IllxEfAJuo=,tag:mrl0FDobiM56iqZYwfKY0A==,type:str]
cloudflare-dns-token: ENC[AES256_GCM,data:8kBtMnByMaHA2hjgJIkyrqXrfDJMp95r5aa9/rhsSZREsLvxEeI/Hx9xFWpf4sscsScB1qiLo+4nhG3K4lo23Kda,iv:OkNGO6cPZWx4mQ5EcxGZH23weAVP/YVHAt+KQN7rl8I=,tag:4tB0XMDOBAb87tIuQtP9Vw==,type:str]
dummy-token: ENC[AES256_GCM,data:BEv3qVyvrUa8AD8HTJ6LQuZweXPWRH7HK2NVm/7zNxRSxLYwdfRvJkcNXOtP7GokKur7FhivIJ6AGymPQj0B+A==,iv:HJOIE39cosnbEUigAVUF9UA/ahF+pgrv5QlJ0CiZU2Q=,tag:G/fT0zL7bPrjJGlRe2Td2Q==,type:str]
users:
    michael-password: ENC[AES256_GCM,data:5RJB7sX5Q+PBvT6QgBE4Y2xbvBhJCXCQnf1ZVEA0FW5P7Rfm4nphbFTpOy4qHemmTmaD9Sueqxa6qXXPS1ZaO1ukDyd9n9qMg3s=,iv:fQImPDrKXS7S9dD2MRVMzLA/7v06qkM1rY4o7e/l2O8=,tag:u0waNgryAcboZ2u5ePAzyg==,type:str]
    sysadmin:
        password: ENC[AES256_GCM,data:TozFra6YLXx/VN3Hu4DGAvrAICPUi/1+AUpDmmTuz4lK+itnroHzCtK+wZuy3sRkjY5ZMHFFptEmWf5XYAOZRwiUMV+0LPHvEco=,iv:GZ9k+shFAIVpaftzWeR1RdEJTtRh2O1Hshz2hmE/qhU=,tag:ugD4yQ+DlBmv7+CWbD0NUg==,type:str]
selene:
    conduwuit:
        registration_token: ENC[AES256_GCM,data:agx9JEag45TeE+VbwUc4ykYxwgHyKjsYIOUu6jwj3kcwUw6klyoJTDnbHS3hfBWpLFeL5XvT4KpamYDMol+8T0REu14hPB6D,iv:AqA0z6VtHKjgb4aJns8oq8YMipgQEvbWv9bx01xf2zI=,tag:sF4tnp73hkaVoAZCrDZuDw==,type:str]
    cloudflare:
        api-token: ENC[AES256_GCM,data:jL2z3Fng79X71dZkvbJv77RT8G+iTqzFv8zLoZSk0XRiP/jiBUPFr54AagCwRTYwy/RW7YghQS2LdlH92qxxVeE=,iv:FCGhtfvjzmPhg7C7SVDIuM6ccMcC34I99yZAI7RWh8M=,tag:dvO8IJFZM0w4icJZUFsLkg==,type:str]
    nginx:
        #ENC[AES256_GCM,data:cdKeRfYs2aGpXxGDwtV7LMWgIocDSDOaxdJHiVJeqx+iEpBfPZip0Om/TV4fKXK855OjsNY6oLsyvsm6YYU=,iv:bjqNNOHCp61OIJy1rQKEU2+b3kqoNyIsL4WJFZSSDsM=,tag:Ih8xXODqnCS/SyYe5W8QFQ==,type:comment]
        estevan: ENC[AES256_GCM,data:71qmHuvSMX30KPuLSXfZfFS3LzTPdq0d5VfgbH3RoJRbZtIehRkZXa2+xEV2/e3t66MHLXviEil2i5qsgBYCrjxBuVW7,iv:uOiJysU+29OYQPXCVv2ItzQH/KeQfTH8JEt2K8+994k=,tag:/pVddesRe+SWS2OUCs6JPw==,type:str]
        urbex: ENC[AES256_GCM,data:fVa4ZVfRY9wv0M5VC0xWT30qz9cEzUvgS/NY7KWQg4Yjn73PsZ8vKWYjPjcYG4Gqq8jgRwZxBOdVQZH+kFp0P35jkw==,iv:4Pr99eG7aoERAoYFmNTVwGtsiH6ZPUr92uORnOTmg1s=,tag:3Hfm0Xm7vBQCJjbhFa7qvA==,type:str]
    affine:
        admin-password: ENC[AES256_GCM,data:ZA85g6XXzauVKLPL,iv:yxgapDckpvw2ZyYf/2bWFCQvV3GQVKGhkKLiDdEwhg0=,tag:L8QmZBNdRFSimkT2m7xLXg==,type:str]
        mailer-env: ENC[AES256_GCM,data:AeLdAOsg6bGG,iv:nHtbZnvt0OKEBPATLCEpKu7O9Z+mz+rLSQCjgfJQ0sY=,tag:9p923XCrwjDhT+eYeVwxpw==,type:str]
e5800:
    ssh_key: ENC[AES256_GCM,data:s/gqEAXCj0IOjvh66g6Tts1u/vkTLr1W/bc2JQsYlUuKrcIg80ZEM9W/WbaGXjUW0eVm7fDQVSYlYKYE1T9JHNuTzh+VyKZ3MSom7l56sWPn/VUlGSPC2L7dKCVs/2VRUQGUMNK5R+ANtkxtCyO+Sh583j27dK3WotOX5AkckRnJcb5AxQ2zq+LBvBdEdaznD5HoaKvVuNQJolHdSEEJ2WujhDAC2ift6TAgEIitCb2wK1m75bT5TpLmOpHLiPr0oVPNwjB7SpWYt7zrMjQAZ4RMGgGYicN0O5T8eUF4tkuray8DARV4b1NDxhouc/jdVanhxGvDSfH4DaCpEpV+uOQHNmd8p2MdUoEzlL64KVyMGXkAHqIdC0mGDVXYZ+I7oxPjY1+yKfEYrEiqSe3nNWXnAv2No4b33GVqsMKVmUlPYer2tMobkRMF+eWdVo4wUrtLfqYN/6YdvLiRfMcmhwpmLuXMxcv3oltrPteCVIqhQMCdadbDKnhsMxyN0HRo71Sb3Y8l9dtmv5x229E/,iv:XkZGNL8KMKZgFvWJ3Vk0MYKEf6nnGWU+HfJz6kjBHmU=,tag:vGfakm4yIhjVkUr8Ix9HXA==,type:str]
    web_password: ENC[AES256_GCM,data:omBNh/E6+Tj1jQ==,iv:MrepkVylANfK5JZMn0iipigoQChkf5rw2WLZA6Fkm8E=,tag:mDLLCvOIjU22v56IuZDMsg==,type:str]
github-token: ENC[AES256_GCM,data:53y3Fe9jdVktMtaZdpa6sf8iSHw2oix4vFRspLeEFX3meBPDp0wa70M=,iv:Y2bON4zcBWhYX3siUuYhUGI3zb2uD9N8v/KNRTSXK6Q=,tag:Em7IET+QdmXgACkPVb1/8w==,type:str]
geoclue:
    gmaps-key: ENC[AES256_GCM,data:kgz8dfatpkV/9DE5TPysjdER212SzmXxXqjskjxIeHlLLpuk7BR/Mg==,iv:CfRcOvdyUFBRZiNkAvroH/k12RpjVYyxI+FGCIGL75Y=,tag:cD7FOrSSzLiydWPVXIxCTw==,type:str]
pirate-weather-key: ENC[AES256_GCM,data:S/bmd/2uHt3q43IJZvmTSA3mo6LGvz0XqfsNVXzLFogR,iv:ccEqrCi8roQQohzRqIdbMJqemMqOUDR1yuytHc5qTDM=,tag:yJrRlIDJ5tk7oGvDHflm7A==,type:str]
affine:
    email-password: ENC[AES256_GCM,data:UQ/+43dXcTlE8ZAJcXh5QTlL9qhAwO2aLKXSHcPrzynwQhjDLw==,iv:4Lxtya68N4RbUqhvkBFPLezvn/NkkDqP/4QrOsd18Q8=,tag:3XSEnf6dhlZa4mgKZUUQeA==,type:str]
    admin-login-password: ENC[AES256_GCM,data:aTVMOZtGwN+2BTOSuQe+UAvtx+e6,iv:7yPXmsgqfQ8YBX31tGAc08ApP/jJTqnauJ4ArcdSrYw=,tag:e5GaolpthT+5T4Cg2U8XWA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUHp0cHZYWGNjaUNhejlH
            L3Z1SmxRenM1V2F1bXNwb3pyUFg0ZFQ4RFdFCmNoK0FjWTJydHo0T05wUlRTL2pt
            dm02aGpNZkhFVFY4WEpnY3NxcnoyeWMKLS0tIDdoMjNwMUppQSswQkUveXdJZlBW
            VmgwTkVFLzk0R25XQWFmTjFYTFlGdkkKAb/DuxBwBaLtGTjHZ0yJbUhsECDq0lA6
            x7yNX+u1RKt9dC87QLbFLKXedcQ9CtUEZtvShz5TTxSmKAOF2lstmQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12h2ljsqesqlh8t00mvtsgmjavus7cgjysus53xxu7yf6f4cvufuszrzx3u
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXeThDdzRkWnozMjBiZ21p
            UlY5N1EwZjdHZk1MdWMzbjkzdmJ1MTdqWVhjCm55cjhWc1Nvd2xva1hYR1FDL044
            RDB1VSt2dEZ1T2oyanh5SmlIKzRiRTQKLS0tIExtaGlpMEl3V09BOXpWTEFMZlRv
            MEgzUFFmWU56TXd3amUrR2tRR0JMRVkKCzwHld1marpHnKT8H0XSS0ABT5Uule8N
            5tQzDZ96uGHZhAfsKpaNqISOxU6keaWgA33U90Fk+/ogPaCePNhwIw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15mmd7sj5trv23azseax4etvuyu0adqckdtvmhuyl5y37te5rz50sm3xts0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRQlE5RWdkQ1p6TmVyTzRu
            aWticm1LcHRjU3p2ZTZTQmdwUENnZ1BGamlRCkxaVm1RalFxVnM1UE1xUTFiblFD
            UWg0YlRRYU9WbEhHRGsrV1M3dkNacm8KLS0tIFA0a1V4WE93b3ltcjZpQnp0bFR4
            WERVNFRUVTlPaHQyQjl0TWMrSHpVM2MKOhqPLbtP+yca8Eo6bRfp4pOCV0jIfeOo
            riZjkfRUILPiNEKDsUEtnoHapsg5wSoAIO5Vyh7eElNQLaY0y80Drg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jstnme4ukmd0cgw09xf53uh7f3lkh05mwrnt5lrs57z0xqgqwf2qh73f9l
    lastmodified: "2026-07-23T12:02:31Z"
    mac: ENC[AES256_GCM,data:m/IBlX3Jr0YtZbLNZlmeAGvX6TnzlOyXO/dUCSvwJokDrXh0fssO44KOhzmDZVJfqqtxJSKa4NZMQ1lDqBXKTHNbr9k3CrgtnZ3EpHa6uQm9Sg1LIupZH5THIq9GF4OdnZvaKshjx/eIAlCwt24S43+Z184G6mA3TZhQ82Rhd/4=,iv:d392CfAwc9NUzWBcCZCp/DFK6gh+DB3JAHBV/R4RAmU=,tag:egfWdwRrrVzeh1czjgTW6A==,type:str]
    pgp:
        - created_at: "2025-06-28T01:32:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwAAAAAAAAAAAQ//cnXhg+qQvso7wFgY6a06BPnekihoN6e/mK11qT8yQMGA
            tW/GqN3uZTH1b9HztGswUkhHaUQItkKu5aJ/hQRiTQJwq61Vdnh17S6Pllhto3Ev
            v0WNBmzDGgjlE+WQyg9vF4mHh97woRVodhQzh0pzCEMEKpcE98fmqnswPzKnMbnI
            +oxOIm3VJuTpGCCBgiIS3FYPgXPuY4w6hYWsFP3320WHnL+mS5f9MZ8tnSerRMdd
            OMTP+6JUcIatA0XgVw3wQga/bk2KWs4dsAvRTl1iuZnHicOyDdRsGA3EUoW6F3Qz
            sWUFJr3CVAY2dYlVNaMpsMuID1XkYNpgb7Ry/krFjEUNU2lCo+CV4ArxAadTlv8r
            OFmG5fe33smSVKX/GI/tDPm2YgwXN4dk+89eeYmB9k+JYrLhr4nwkSlD7wcltrSM
            cpoSFP5Xtf+Ms2pUyS+96n2ndWxedZHCpr+I+H7wmS7HRpohgTkm5TGrUn4OD47g
            nwcH/AkpQg3IobqGz5LRA2xkW7ikkbVEmesl1aYUX6levsiH4BPoSKfzVJ2Yn/FE
            rJ6TxoDDm0Ep/TfSc3r1V7rScIT4xdXkAQa+C3dSXEazl0aAhW1KRWe327/eaEWp
            Dx1gY5JmHpMDhuZpS+78KrHDzRItipoLf5VKQFQT7uxByT4s3nJ46alW/BKpJc3S
            XAFuepAoIZe2fg/EVlIdkY26iWhuR0Q9agQVVZYse8K7Ez0yQHBC8XA0prK42w9T
            R2MYV774CCCwLIefc0gKC0/fv6PbRuhwg7GrTeNwf6alrWWYUFTaqSLULrIR
            =nAG1
            -----END PGP MESSAGE-----
          fp: 8d12991f5558c50170b2779c781146b0b5f95f64
    unencrypted_suffix: _unencrypted
    version: 3.13.2
